### ISSUE TITLE
how to view satellite ?

### ISSUE THREAD

**Issue by tastangh** [lucas-bremond/satellite-visualizer#1]
Hello,
thanks for this plugin. I worked on this plugin but I showed some problems.

I get position data from influxdb
```
from(bucket: "trick")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_field"] == "satelliteSO.SATELLITE_Y.Q_BI[0]" or r["_field"] == "satelliteSO.SATELLITE_Y.Q_BI[1]" or r["_field"] == "satelliteSO.SATELLITE_Y.Q_BI[2]" or r["_field"] == "satelliteSO.SATELLITE_Y.Q_BI[3]" or r["_field"] == "satelliteSO.SATELLITE_Y.R_ECI[0]" or r["_field"] == "satelliteSO.SATELLITE_Y.R_ECI[1]" or r["_field"] == "satelliteSO.SATELLITE_Y.R_ECI[2]")
  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

but I didn't see any satellite or orbit.

![Capture1](https://github.com/lucas-bremond/satellite-visualizer/assets/54810017/7951f8ab-23d1-4df6-9ade-8f8ac3830b85)
![Capture2](https://github.com/lucas-bremond/satellite-visualizer/assets/54810017/e6227667-257d-49cd-921f-91f3e222ea65)

**Comment by tastangh** [comment]
@lucas-bremond

**Comment by lucas-bremond** [comment]
Could you post a screenshot of the table view to see the structure of your dataset?

**Comment by tastangh** [comment]
Hello, first of all, I would like to inform you that your answer is very important to me.

When I examined it after your answer, I realized that there was an error in my query. First, I created the query to obtain the image in the 1st screenshot with the table plugin.

When I entered the same query into the satellite visualizer plugin, I received an error as in the 2nd screenshot.

I thought this was because my values ​​were in the form of R_ECI Q_BI and latitude did not convert into longitude altitude. Don't you think so?
Thank you very much for everything. @lucas-bremond 


![1](https://github.com/lucas-bremond/satellite-visualizer/assets/54810017/5557ade6-cdb0-4352-92b2-6b379dbe158f)
![2](https://github.com/lucas-bremond/satellite-visualizer/assets/54810017/77b483ce-938d-42fc-bf29-afb191085e9f)

**Comment by lucas-bremond** [comment]
The order of yours fields do not seem to follow the format documented in the [README](https://github.com/lucas-bremond/satellite-visualizer/blob/main/README.md): 

![image](https://github.com/lucas-bremond/satellite-visualizer/assets/4208560/f7608cb1-16fa-4bae-ada8-799a397da5d6)

Could you try to follow the exact same order?

Also, position is expected in `lon/lat/alt, not `r_ECI`.

**Comment by tastangh** [comment]
Thank you very much for the answer.
I had read Readme, but I still wanted to try it because the values ​​from my Simulator came as R_ECI. I'll try again using lat/long/alt conversions.

**Comment by tastangh** [comment]
Hello again, I try but don't convert ECI TO LLA. How do I change the reference frame LLA to ECI for Cesium?

**Comment by lucas-bremond** [comment]
> How do I change the reference frame LLA to ECI for Cesium?

You cannot, in the current version of the plugin. It expects LLAs to be provided.

**Comment by micaethang** [comment]
@lucas-bremond
I want to know how to display information about **coordinates (longitude, latitude, altitude)** and **Orientation (Quaternion)** in the tooltip when the satellite moves (animation).

I look forward to receiving your help!

**Comment by micaethang** [comment]
@lucas-bremond

**Comment by micaethang** [comment]
@lucas-bremond 
Hello, for me this plugin is amazing.
I know that this plugin doesn't have the above feature yet and you're probably very busy, but I would be very grateful if I could know a solution to solve the above problem.

**Comment by tastangh** [comment]
Hello everyone,
@lucas-bremond @micaethang 

I fixed this problem with pymap3d(astropy-based) .

my eci data type is km so, I convert it to m.

```
# Define a function to convert R_ECI to ECEF
def eci_to_ecef(eci_x, eci_y, eci_z, time_utc):
    eci_x = eci_x * 1000
    eci_y = eci_y * 1000
    eci_z = eci_z * 1000
    ecef = pm.eci2ecef(eci_x, eci_y, eci_z,time_utc)
    return ecef

# Define a function to convert ECEF to LLA
def ecef_to_lla(ecef):
    lla = pm.ecef2geodetic(ecef[0], ecef[1], ecef[2])
    return lla
```
 
```
  # Extract values from the records
                eci_x = record_x.values["_value"]
                eci_y = record_y.values["_value"]
                eci_z = record_z.values["_value"]
                jd_time = record_jd.values["_value"]
                time_utc = Time(jd_time, format="jd", scale="utc").datetime
                # time_utc = record_x.get_time()  # Assume all records have the same timestamp

                # Combine ECI_X, ECI_Y, ECI_Z
                r_eci = [eci_x, eci_y, eci_z]
                print(f"R_ECI Values: X={r_eci[0]}, Y={r_eci[1]}, Z={r_eci[2]}, Time={time_utc}")


                # Convert ECI to ECEF
                ecef = eci_to_ecef(r_eci[0], r_eci[1], r_eci[2],time_utc)
                print(f"ecef Values: X={ecef[0]},6 Y={ecef[1]}, Z={ecef[2]}")

                # Convert ECEF to LLA
                lla = ecef_to_lla(ecef)
                print(f"LLA Coordinates: Latitude={lla[0]}, Longitude={lla[1]}, Altitude={lla[2]}, Time={time_utc}")
```

all parameters for the satellite visualizer should be added Grafana query section.
![1](https://github.com/lucas-bremond/satellite-visualizer/assets/54810017/ab1cc32b-e1d9-45da-9db1-4ecb5b18a700)
![2](https://github.com/lucas-bremond/satellite-visualizer/assets/54810017/47447f17-64bd-4f67-be9a-3b1d13ea002a)

**Comment by tastangh** [comment]
@lucas-bremond 
My new problem is about importing the satellite model. I uploaded my model to cesium ion, I have an asset id and access token, but I cannot find the asset uri. How can I generate asset uri or gltf?

**Comment by lucas-bremond** [comment]
We've just merged a PR from @vishwa2710 which adds the ability to provide coordinates in ECI/ECEF and LLA:

https://github.com/lucas-bremond/satellite-visualizer/pull/3

This issue should now be resolved.
